# Generated by Django 4.2 on 2023-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_remove_state_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='energy_yield',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
