# Generated by Django 4.2 on 2023-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('yield', models.IntegerField()),
                ('state', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['state'],
            },
        ),
    ]
